# Generated by Django 5.2.6 on 2025-09-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_tour_remove_tourregistration_tour_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourregistration',
            name='tour',
        ),
        migrations.AddField(
            model_name='tourregistration',
            name='tour_name',
            field=models.CharField(default='Конный тур по Ала-Арче', max_length=200),
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
