# Generated by Django 5.2.6 on 2025-09-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_remove_tourregistration_tour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
