# Generated by Django 5.2.6 on 2025-09-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_person_review_tourregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourregistration',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='TourRegistration',
        ),
    ]
