# Generated by Django 5.2.6 on 2025-09-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_tourregistration_person_delete_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=100),
        ),
    ]
