# Generated by Django 5.2.6 on 2025-09-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
    ]
